PKG_INSTALL:=1

ifneq ($(findstring c,$(OPENWRT_VERBOSE)),)
  MAKE_FLAGS+=VERBOSE=1
endif

CMAKE_SOURCE_DIR:=.

ifeq ($(CONFIG_CCACHE),)
 ifeq ($(CONFIG_EXTERNAL_TOOLCHAIN),)
  CMAKE_C_COMPILER:=$(TOOLCHAIN_DIR)/bin/$(TARGET_CC)
  CMAKE_C_COMPILER_ARG1:=
  CMAKE_CXX_COMPILER:=$(TOOLCHAIN_DIR)/bin/$(TARGET_CXX)
  CMAKE_CXX_COMPILER_ARG1:=
 else
  CMAKE_C_COMPILER:=$(shell which $(TARGET_CC))
  CMAKE_C_COMPILER_ARG1:=
  CMAKE_CXX_COMPILER:=$(shell which $(TARGET_CXX))
  CMAKE_CXX_COMPILER_ARG1:=
 endif
else
  CCACHE:=$(shell which ccache)
  ifeq ($(CCACHE),)
    CCACHE:=$(STAGING_DIR_HOST)/bin/ccache
  endif
  CMAKE_C_COMPILER:=$(CCACHE)
  CMAKE_C_COMPILER_ARG1:=$(filter-out ccache,$(TARGET_CC))
  CMAKE_CXX_COMPILER:=$(CCACHE)
  CMAKE_CXX_COMPILER_ARG1:=$(filter-out ccache,$(TARGET_CXX))
endif

ifeq ($(CONFIG_DEBUG),y)
  CMAKE_TYPE:=Debug
else
  CMAKE_TYPE:=Release
endif

define Build/Configure/Default
	(cd $(PKG_BUILD_DIR); \
		CFLAGS="$(TARGET_CFLAGS) $(EXTRA_CFLAGS)" \
		CXXFLAGS="$(TARGET_CFLAGS) $(EXTRA_CFLAGS)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(EXTRA_LDFLAGS)" \
		cmake \
			-D CMAKE_SYSTEM_NAME=Linux \
			-D CMAKE_SYSTEM_VERSION=1 \
			-D CMAKE_SYSTEM_PROCESSOR=$(ARCH) \
			-D CMAKE_BUILD_TYPE=$(CMAKE_TYPE) \
			-D CMAKE_C_FLAGS_RELEASE="-DNDEBUG" \
			-D CMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" \
			-D CMAKE_C_FLAGS_DEBUG="" \
			-D CMAKE_CXX_FLAGS_DEBUG="" \
			-D CMAKE_C_COMPILER="$(CMAKE_C_COMPILER)" \
			-D CMAKE_C_COMPILER_ARG1="$(CMAKE_C_COMPILER_ARG1)" \
			-D CMAKE_CXX_COMPILER="$(CMAKE_CXX_COMPILER)" \
			-D CMAKE_CXX_COMPILER_ARG1="$(CMAKE_CXX_COMPILER_ARG1)" \
			-D CMAKE_EXE_LINKER_FLAGS:STRING="$(TARGET_LDFLAGS)" \
			-D CMAKE_MODULE_LINKER_FLAGS:STRING="$(TARGET_LDFLAGS)" \
			-D CMAKE_SHARED_LINKER_FLAGS:STRING="$(TARGET_LDFLAGS)" \
			-D CMAKE_FIND_ROOT_PATH=$(STAGING_DIR) \
			-D CMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH \
			-D CMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
			-D CMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
			-D CMAKE_STRIP=: \
			-D CMAKE_INSTALL_PREFIX=/usr \
			-D DL_LIBRARY=$(STAGING_DIR) \
			-D CMAKE_PREFIX_PATH=$(STAGING_DIR)/usr \
			$(CMAKE_OPTIONS) \
		$(CMAKE_SOURCE_DIR) \
	)
endef

define Build/InstallDev/cmake
	$(INSTALL_DIR) $(1)
	$(CP) $(PKG_INSTALL_DIR)/* $(1)/
endef

Build/InstallDev = $(if $(CMAKE_INSTALL),$(Build/InstallDev/cmake))
